# Generated by Django 6.0.6 on 2026-06-12 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DeptNo', models.AutoField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=100, unique=True)),
                ('Location', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpId', models.AutoField(primary_key=True, serialize=False)),
                ('Ename', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=6)),
                ('Phone', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=100, unique=True)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Address', models.CharField(max_length=150)),
                ('DeptNo', models.ForeignKey(db_column='DeptNo', on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
    ]
